name: gripsraum/hero
title: LLL:EXT:my_sitepackage/ContentBlocks/ContentElements/hero/language/labels.xlf:title
group: default
description: LLL:EXT:my_sitepackage/ContentBlocks/ContentElements/hero/language/labels.xlf:description
prefixFields: true
prefixType: full
basics:
  - TYPO3/Appearance
  - TYPO3/Links
fields:
  - identifier: header
    useExistingField: true
  - identifier: section_anchor
    type: Text
    useExistingField: true
    label: LLL:EXT:my_sitepackage/Resources/Private/Language/locallang.xlf:anchor_id.label
    description: LLL:EXT:my_sitepackage/Resources/Private/Language/locallang.xlf:anchor_id.description
  - identifier: bodytext
    useExistingField: true
    label: "Text links"
    enableRichtext: true
  - identifier: show_left
    type: Checkbox
    renderType: checkboxToggle
    label: "Linke Spalte anzeigen"
    default: true
  - identifier: show_right
    type: Checkbox
    renderType: checkboxToggle
    label: "Rechte Spalte anzeigen"
    default: true
  - identifier: right_text
    type: Textarea
    label: "Text rechts"
    enableRichtext: true
assets:
  css:
    - assets/frontend.scss
