name: gripsraum/hero
title: LLL:EXT:my_sitepackage/ContentBlocks/ContentElements/hero/language/labels.xlf:title
group: default
description: LLL:EXT:my_sitepackage/ContentBlocks/ContentElements/hero/language/labels.xlf:description
prefixFields: true
prefixType: full
basics:
  - TYPO3/Appearance
  - TYPO3/Links
fields:
  - identifier: header
    useExistingField: true
  - identifier: section_anchor
    type: Text
    useExistingField: true
    label: LLL:EXT:my_sitepackage/Resources/Private/Language/locallang.xlf:anchor_id.label
    description: LLL:EXT:my_sitepackage/Resources/Private/Language/locallang.xlf:anchor_id.description
  - identifier: bodytext
    useExistingField: true
    label: "Einleitung (Über mich)"
  - identifier: about_image
    type: File
    label: "Profilbild"
    maxitems: 1
    allowed: common-image-types
  - identifier: faq_header
    type: Text
    label: "Überschrift (FAQ)"
    default: "HÄUFIGE FRAGEN"
  - identifier: faq_items
    type: Collection
    label: LLL:EXT:my_sitepackage/ContentBlocks/ContentElements/faq/language/labels.xlf:faq_items.label
    labelField: question
    minitems: 1
    maxitems: 20
    appearance:
      collapseAll: true
      levelLinksPosition: bottom
    fields:
      - identifier: question
        type: Text
        label: LLL:EXT:my_sitepackage/ContentBlocks/ContentElements/faq/language/labels.xlf:question.label
        required: true
      - identifier: answer
        type: Textarea
        label: LLL:EXT:my_sitepackage/ContentBlocks/ContentElements/faq/language/labels.xlf:answer.label
        enableRichtext: true
        required: true
assets:
  css:
    - assets/frontend.scss
  js:
    - assets/frontend.js
