base: /
dependencies:
  - typo3/fluid-styled-content
  - gripsraum/my-sitepackage
  - typo3/form
  - typo3/email
languages:
  -
    title: German
    enabled: true
    locale: de_DE.utf8
    hreflang: ''
    base: /
    websiteTitle: ''
    navigationTitle: ''
    flag: de
    languageId: 0
rootPageId: 1
websiteTitle: ''
