base: 'https://maidem.de/'
dependencies:
  - typo3/fluid-styled-content
  - gripsraum/my-sitepackage
  - typo3/form
  - typo3/email
  - denkwerk/mosparo-form
  - georgringer/news
languages:
  -
    title: German
    enabled: true
    locale: de_DE.utf8
    hreflang: ''
    base: 'https://maidem.de/'
    websiteTitle: ''
    navigationTitle: ''
    flag: de
    languageId: 0
rootPageId: 1
routeEnhancers:
  NewsPluginDetail:
    type: Extbase
    extension: News
    plugin: Pi1
    limitToPages:
      - 30
      - 31
    routes:
      -
        routePath: '/{news-title}'
        _controller: 'News::detail'
        _arguments:
          news-title: news
    defaultController: 'News::list'
    aspects:
      news-title:
        type: PersistedAliasMapper
        tableName: tx_news_domain_model_news
        routeFieldName: path_segment
websiteTitle: ''
