form.contact.recipientEmail: connect@maidem.de
form.contact.privacyPageUid: 15
plugin.tx_mosparoform.settings.projects.default.publicServer: 'https://protect.maik-demuth.de'
plugin.tx_mosparoform.settings.projects.default.verifyServer: 'https://protect.maik-demuth.de'
plugin.tx_mosparoform.settings.projects.default.uuid: ce81c46b-6219-4514-be5a-c3dfc70ce41b
plugin.tx_mosparoform.settings.projects.default.publicKey: I8_K2QCbjhFuq0Mgmlz7oodN_vzxtoF1pTOdaS4hBbc
plugin.tx_mosparoform.settings.projects.default.privateKey: wetC-sP-SJ5Ld4-ZW0Ff4896hkHE2I5sniFDxx7dc3c
nav.homeTitle: Kurzprofil
nav.techTitle: Fokus
