version: "3.8"

services:
  portfolio:
    image: ${DOCKER_REGISTRY_URL:-ghcr.io}/${DOCKER_REGISTRY_USERNAME:-maidem}/portfolio-v1:${DOCKER_REGISTRY_TAG:-latest}
    container_name: portfolio-app
    restart: always
    expose:
      - "80"
    environment:
      # TYPO3 Environment Variables
      TYPO3_CONTEXT: ${TYPO3_CONTEXT:-Production}
      TYPO3_DATABASE_HOST: ${TYPO3_DATABASE_HOST:-db}
      TYPO3_DATABASE_PORT: ${TYPO3_DATABASE_PORT:-3306}
      TYPO3_DATABASE_NAME: ${TYPO3_DATABASE_NAME:-typo3}
      TYPO3_DATABASE_USERNAME: ${TYPO3_DATABASE_USERNAME:-typo3}
      TYPO3_DATABASE_PASSWORD: ${TYPO3_DATABASE_PASSWORD}
    volumes:
      - ./var:/var/www/html/var
      - ./public/fileadmin:/var/www/html/public/fileadmin
      - ./public/typo3temp:/var/www/html/public/typo3temp
    networks:
      - portfolio-network
      - coolify # Zwingt den Container in das Netzwerk von Traefik

networks:
  portfolio-network:
    driver: bridge
  coolify:
    external: true # Sagt Docker, dass es das globale Coolify-Netzwerk nutzen soll
