imports:
    - { resource: "EXT:rte_ckeditor/Configuration/RTE/Processing.yaml" }
    - { resource: "EXT:rte_ckeditor/Configuration/RTE/Editor/Base.yaml" }
    - { resource: "EXT:rte_ckeditor/Configuration/RTE/Editor/Plugins.yaml" }

editor:
    config:
        contentsCss: "EXT:my_sitepackage/Resources/Public/Css/rte.css"

        stylesSet:
            - { name: "Lead", element: "p", attributes: { 'class': 'lead' } }

        format_tags: "p;h2;h3"

        justifyClasses:
            - text-left
            - text-center
            - text-right
            - text-justify

        removePlugins:
            - image

        importModules:
            - { module: '@ckeditor/ckeditor5-code-block', exports: [ 'CodeBlock' ] }

        toolbar:
            items:
                - heading
                - "|"
                - bold
                - italic
                - "|"
                - bulletedList
                - numberedList
                - outdent
                - indent
                - alignment
                - "|"
                - link
                - "|"
                - undo
                - redo
                - "|"
                - insertTable
                - specialCharacters
                - "|"
                - codeBlock

        codeBlock:
            languages:
                - { language: 'plaintext', label: 'Plain text' }
                - { language: 'php', label: 'PHP' }
                - { language: 'javascript', label: 'JavaScript' }
                - { language: 'typescript', label: 'TypeScript' }
                - { language: 'css', label: 'CSS' }
                - { language: 'html', label: 'HTML' }
                - { language: 'bash', label: 'Bash' }
                - { language: 'json', label: 'JSON' }
                - { language: 'yaml', label: 'YAML' }
                - { language: 'typoscript', label: 'TypoScript' }
                - { language: 'twig', label: 'Fluid' }
                - { language: 'docker', label: 'Docker' }
