name: gripsraum/banner
title: "LLL:EXT:my_sitepackage/ContentBlocks/ContentElements/banner/language/labels.xlf:title"
group: default
description: "LLL:EXT:my_sitepackage/ContentBlocks/ContentElements/banner/language/labels.xlf:description"
prefixFields: true
prefixType: full
fields:
  - identifier: header
    useExistingField: true
assets:
  css:
    - assets/frontend.scss
  javaScriptModules:
    - assets/frontend.js
