name: gripsraum/page-header
title: LLL:EXT:my_sitepackage/ContentBlocks/ContentElements/page-header/language/labels.xlf:title
group: portfolio
description: LLL:EXT:my_sitepackage/ContentBlocks/ContentElements/page-header/language/labels.xlf:description
prefixFields: true
prefixType: full
fields:
  - identifier: header
    useExistingField: true
  - identifier: section_anchor
    type: Text
    useExistingField: true
    label: LLL:EXT:my_sitepackage/Resources/Private/Language/locallang.xlf:anchor_id.label
    description: LLL:EXT:my_sitepackage/Resources/Private/Language/locallang.xlf:anchor_id.description
assets:
  css:
    - assets/frontend.scss
