services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Gripsraum\PdfExport\:
    resource: "../Classes/*"
    exclude: "../Classes/Domain/Model/*"

  Gripsraum\PdfExport\Controller\PdfExportController:
    public: true
