name: gripsraum/skills
typeName: gripsraum_skills
group: portfolio
prefixFields: true
prefixType: full
fields:
  - identifier: header
    useExistingField: true
  - identifier: section_anchor
    type: Text
    useExistingField: true
    label: LLL:EXT:my_sitepackage/Resources/Private/Language/locallang.xlf:anchor_id.label
    description: LLL:EXT:my_sitepackage/Resources/Private/Language/locallang.xlf:anchor_id.description
  - identifier: skill_items
    type: Collection
    label: Skills
    labelField: skill_name
    appearance:
      collapseAll: true
      levelLinksPosition: bottom
    fields:
      - identifier: skill_name
        type: Text
        label: Skill
        required: true
      - identifier: filter_group
        type: Text
        label: Filtergruppe(n)
        description: 'Kommagetrennt für mehrere Gruppen, z. B. "Frontend, Design"'
  - identifier: show_pdf_export_button
    type: Checkbox
    renderType: checkboxToggle
    label: "PDF-Export Button anzeigen"
    default: false
