name: gripsraum/skills
typeName: gripsraum_skills
group: portfolio
prefixFields: true
prefixType: full
fields:
  - identifier: header
    useExistingField: true
  - identifier: section_anchor
    type: Text
    useExistingField: true
    label: LLL:EXT:my_sitepackage/Resources/Private/Language/locallang.xlf:anchor_id.label
    description: LLL:EXT:my_sitepackage/Resources/Private/Language/locallang.xlf:anchor_id.description
  - identifier: skill_collections
    type: Collection
    label: LLL:EXT:my_sitepackage/ContentBlocks/ContentElements/skills/language/labels.xlf:skill_collections.label
    description: LLL:EXT:my_sitepackage/ContentBlocks/ContentElements/skills/language/labels.xlf:skill_collections.description
    appearance:
      levelLinksPosition: both
    fields:
      - identifier: skill_name
        type: Text
        label: LLL:EXT:my_sitepackage/ContentBlocks/ContentElements/skills/language/labels.xlf:skill_name.label
      - identifier: skill_category
        type: Text
        label: LLL:EXT:my_sitepackage/ContentBlocks/ContentElements/skills/language/labels.xlf:skill_category.label
        description: LLL:EXT:my_sitepackage/ContentBlocks/ContentElements/skills/language/labels.xlf:skill_category.description
  - identifier: show_pdf_export_button
    type: Checkbox
    renderType: checkboxToggle
    label: "PDF-Export Button anzeigen"
    default: false
