name: gripsraum/my-sitepackage
label: "My SitePackage"
dependencies:
  - typo3/fluid-styled-content
  - typo3/fluid-styled-content-css
  - typo3/form
  - denkwerk/mosparo-form
  - gripsraum/pdf-export
