name: gripsraum/news-article
typeName: gripsraum_newsarticle
group: default
prefixFields: true
prefixType: full
basics:
  - TYPO3/Appearance
fields:
  - identifier: header
    useExistingField: true
  - identifier: section_anchor
    type: Text
    useExistingField: true
    label: LLL:EXT:my_sitepackage/Resources/Private/Language/locallang.xlf:anchor_id.label
    description: LLL:EXT:my_sitepackage/Resources/Private/Language/locallang.xlf:anchor_id.description
  - identifier: project_date
    type: DateTime
    label: LLL:EXT:my_sitepackage/ContentBlocks/ContentElements/news-article/language/labels.xlf:project_date.label
  - identifier: teaser_text
    type: Textarea
    label: LLL:EXT:my_sitepackage/ContentBlocks/ContentElements/news-article/language/labels.xlf:teaser_text.label
    required: true
  - identifier: bodytext
    useExistingField: true
  - identifier: images
    type: File
    label: LLL:EXT:my_sitepackage/ContentBlocks/ContentElements/news-article/language/labels.xlf:images.label
    maxitems: 5
    allowed: common-image-types
