name: gripsraum/news-article
group: default
fields:
  - identifier: header
    useExistingField: true
    label: Headline
  - identifier: project_date
    type: DateTime
    label: Veröffentlichungsdatum
  - identifier: teaser_image
    type: File
    label: Teaser-Bild (Für die Anzeige in der Liste)
    maxitems: 1
    allowed: common-image-types
  - identifier: teaser_text
    type: Textarea
    label: Kurzfassung (Für die Liste)
  - identifier: bodytext
    useExistingField: true
    label: Der eigentliche Artikel (Haupttext)
    enableRichtext: true
